site_name: Orebit
site_url: https://stevendesu.github.io/orebit-1.21.4
docs_dir: .
site_dir: ../docs_site
repo_url: https://github.com/stevendesu/orebit-1.21.4
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes
plugins:
  - search
  - offline
markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
